<?php

namespace AppBundle\Repository;

/**
 * AbscentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbscentRepository extends \Doctrine\ORM\EntityRepository
{
}
