<?php

namespace AppBundle\Repository;

/**
 * CrecheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrecheRepository extends \Doctrine\ORM\EntityRepository
{
}
