<?php

namespace AppBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{

    function findByNomEnfant($data)
    {
        return $this->createQueryBuilder("e")
            ->where('e.nom LIKE :nom')
            ->setParameter("nom", "%$data%")
            ->orderBy('e.id', 'DESC')
            ->getQuery()->getResult();
    }

}
