<?php

namespace AppBundle\Repository;

/**
 * EnfantMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantMaterielRepository extends \Doctrine\ORM\EntityRepository
{
}
