<?php

namespace AppBundle\Repository;

/**
 * EnfantHoraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantHoraireRepository extends \Doctrine\ORM\EntityRepository
{
}
