<?php

namespace AppBundle\Repository;

/**
 * FicheInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
