<?php

namespace AppBundle\Repository;

/**
 * historiquepaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriquepaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
