<?php

namespace AppBundle\Repository;

/**
 * LienfamillialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienfamillialeRepository extends \Doctrine\ORM\EntityRepository
{
    function findtuteurEnfant()
    {
        return $this->createQueryBuilder("l")

            ->orderBy('l.tuteur', 'DESC')
            ->getQuery()->getResult();
    }
}
