<?php

namespace AppBundle\Repository;

/**
 * MemoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoRepository extends \Doctrine\ORM\EntityRepository
{
}
