<?php

namespace AppBundle\Repository;

/**
 * paiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends \Doctrine\ORM\EntityRepository
{

	function paiement_impayer(){
		 return $this->createQueryBuilder("p")
                ->where('p.restapayer != :prix')   
                ->setParameter("prix", 0)
                ->orderBy('p.id', 'DESC')
                ->getQuery()->getResult();
	}
}
