<?php

namespace AppBundle\Repository;

/**
 * presenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class presenceRepository extends \Doctrine\ORM\EntityRepository
{
}
