<?php

namespace AppBundle\Repository;

/**
 * VaccinenattenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccinenattenteRepository extends \Doctrine\ORM\EntityRepository
{
}
