<?php

namespace AppBundle\Repository;

/**
 * VaccinerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccinerRepository extends \Doctrine\ORM\EntityRepository
{



}
