<?php

namespace AppBundle\Repository;

/**
 * VaccinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccinRepository extends \Doctrine\ORM\EntityRepository
{
    function Vacciner_enfant($enfant)
    {

       /* return $this->createQueryBuilder("v")
            ->leftJoin("AppBundle\\Entity\\Vacciner", "c",'WITH', 'c.vaccin = v.id')
            ->where('c.enfant = :enfant')
            //->andWhere('c.vaccin != v.id')
            ->setParameter("enfant", $enfant)
            ->getQuery()->getResult();*/

        $conn = $this->getEntityManager()->getConnection();

        $sql = '
        SELECT *
        FROM vaccin v
        WHERE v.id  NOT IN (
        SELECT c.vaccin
        FROM vacciner c
         WHERE c.enfant = :enfant
        )
       
        ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['enfant' => $enfant]);
        // returns an array of arrays (i.e. a raw data set)
        return $stmt->fetchAll();

    }
}
