<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMbkobyz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMbkobyz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMbkobyz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMbkobyz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMbkobyz\appProdProjectContainer(array(
    'container.build_hash' => 'Mbkobyz',
    'container.build_id' => '96eb7cee',
    'container.build_time' => 1578315055,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMbkobyz');
