<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'artgris_bundle_file_manager.service.filemanager_service' shared service.

return $this->services['artgris_bundle_file_manager.service.filemanager_service'] = new \Artgris\Bundle\FileManagerBundle\Service\FilemanagerService($this->parameters['artgris_file_manager'], $this);
