<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\MaterielController' shared autowired service.

return $this->services['AppBundle\Controller\MaterielController'] = new \AppBundle\Controller\MaterielController();
