<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.rss1vus' shared service.

return $this->services['service_locator.rss1vus'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('medicament' => function () {
    $f = function (\AppBundle\Entity\Medicament $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Medicament']) ? $this->services['autowired.AppBundle\Entity\Medicament'] : ($this->services['autowired.AppBundle\Entity\Medicament'] = new \AppBundle\Entity\Medicament())) && false ?: '_'});
}));
