<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ut91jdu' shared service.

return $this->services['service_locator.ut91jdu'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('enfant' => function () {
    $f = function (\AppBundle\Entity\Enfant $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Enfant']) ? $this->services['autowired.AppBundle\Entity\Enfant'] : ($this->services['autowired.AppBundle\Entity\Enfant'] = new \AppBundle\Entity\Enfant())) && false ?: '_'});
}));
