<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.seyxczp' shared service.

return $this->services['service_locator.seyxczp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('vacciner' => function () {
    $f = function (\AppBundle\Entity\Vacciner $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Vacciner']) ? $this->services['autowired.AppBundle\Entity\Vacciner'] : ($this->services['autowired.AppBundle\Entity\Vacciner'] = new \AppBundle\Entity\Vacciner())) && false ?: '_'});
}));
