<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ljtnhej' shared service.

return $this->services['service_locator.ljtnhej'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('memo' => function () {
    $f = function (\AppBundle\Entity\Memo $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Memo']) ? $this->services['autowired.AppBundle\Entity\Memo'] : ($this->services['autowired.AppBundle\Entity\Memo'] = new \AppBundle\Entity\Memo())) && false ?: '_'});
}));
