<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.dkkj8hq' shared service.

return $this->services['service_locator.dkkj8hq'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('activite' => function () {
    $f = function (\AppBundle\Entity\Activite $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Activite']) ? $this->services['autowired.AppBundle\Entity\Activite'] : ($this->services['autowired.AppBundle\Entity\Activite'] = new \AppBundle\Entity\Activite())) && false ?: '_'});
}));
