<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.rsbed0j' shared service.

return $this->services['service_locator.rsbed0j'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('vaccin' => function () {
    $f = function (\AppBundle\Entity\Vaccin $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Vaccin']) ? $this->services['autowired.AppBundle\Entity\Vaccin'] : ($this->services['autowired.AppBundle\Entity\Vaccin'] = new \AppBundle\Entity\Vaccin())) && false ?: '_'});
}));
