<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.vxsnv02' shared service.

return $this->services['service_locator.vxsnv02'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('tuteur' => function () {
    $f = function (\AppBundle\Entity\Tuteur $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Tuteur']) ? $this->services['autowired.AppBundle\Entity\Tuteur'] : ($this->services['autowired.AppBundle\Entity\Tuteur'] = new \AppBundle\Entity\Tuteur())) && false ?: '_'});
}));
