<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.jwsq3or' shared service.

return $this->services['service_locator.jwsq3or'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('paiement' => function () {
    $f = function (\AppBundle\Entity\Paiement $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Paiement']) ? $this->services['autowired.AppBundle\Entity\Paiement'] : ($this->services['autowired.AppBundle\Entity\Paiement'] = new \AppBundle\Entity\Paiement())) && false ?: '_'});
}));
