<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.0eqgiwl' shared service.

return $this->services['service_locator.0eqgiwl'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('poste' => function () {
    $f = function (\AppBundle\Entity\Poste $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Poste']) ? $this->services['autowired.AppBundle\Entity\Poste'] : ($this->services['autowired.AppBundle\Entity\Poste'] = new \AppBundle\Entity\Poste())) && false ?: '_'});
}));
