<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.hekym8k' shared service.

return $this->services['service_locator.hekym8k'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('vaccinenattente' => function () {
    $f = function (\AppBundle\Entity\Vaccinenattente $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Vaccinenattente']) ? $this->services['autowired.AppBundle\Entity\Vaccinenattente'] : ($this->services['autowired.AppBundle\Entity\Vaccinenattente'] = new \AppBundle\Entity\Vaccinenattente())) && false ?: '_'});
}));
