<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gmkagqc' shared service.

return $this->services['service_locator.gmkagqc'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('creche' => function () {
    $f = function (\AppBundle\Entity\Creche $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Creche']) ? $this->services['autowired.AppBundle\Entity\Creche'] : ($this->services['autowired.AppBundle\Entity\Creche'] = new \AppBundle\Entity\Creche())) && false ?: '_'});
}));
