<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.uiy31m4' shared service.

return $this->services['service_locator.uiy31m4'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('materiel' => function () {
    $f = function (\AppBundle\Entity\Materiel $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Materiel']) ? $this->services['autowired.AppBundle\Entity\Materiel'] : ($this->services['autowired.AppBundle\Entity\Materiel'] = new \AppBundle\Entity\Materiel())) && false ?: '_'});
}));
