<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.0tlg6qg' shared service.

return $this->services['service_locator.0tlg6qg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('historiquepaiement' => function () {
    $f = function (\AppBundle\Entity\Historiquepaiement $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Historiquepaiement']) ? $this->services['autowired.AppBundle\Entity\Historiquepaiement'] : ($this->services['autowired.AppBundle\Entity\Historiquepaiement'] = new \AppBundle\Entity\Historiquepaiement())) && false ?: '_'});
}));
