<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.rnbpt9t' shared service.

return $this->services['service_locator.rnbpt9t'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('abscent' => function () {
    $f = function (\AppBundle\Entity\Abscent $v) { return $v; }; return $f(${($_ = isset($this->services['autowired.AppBundle\Entity\Abscent']) ? $this->services['autowired.AppBundle\Entity\Abscent'] : ($this->services['autowired.AppBundle\Entity\Abscent'] = new \AppBundle\Entity\Abscent())) && false ?: '_'});
}));
