<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ksraimg' shared service.

return $this->services['service_locator.ksraimg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('updater' => function () {
    $f = function (\AppBundle\Service\FileUploader $v = null) { return $v; }; return $f(${($_ = isset($this->services['AppBundle\Service\FileUploader']) ? $this->services['AppBundle\Service\FileUploader'] : ($this->services['AppBundle\Service\FileUploader'] = new \AppBundle\Service\FileUploader())) && false ?: '_'});
}));
