<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'autowired.AppBundle\Entity\Vaccin' shared autowired service.

return $this->services['autowired.AppBundle\Entity\Vaccin'] = new \AppBundle\Entity\Vaccin();
