<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheInscription extends \AppBundle\Entity\FicheInscription implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'enfant', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'attente', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'craintes', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'remarque', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'periode', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'horaire', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'autorisation', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'dateinscription', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'allergie', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'mangeavecaide', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'oeuf', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'poisson', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'viande', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'couche', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'laitqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'changeqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'doudouqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'cqqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'mdqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'biberonqte'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'enfant', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'attente', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'craintes', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'remarque', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'periode', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'horaire', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'autorisation', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'dateinscription', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'allergie', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'mangeavecaide', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'oeuf', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'poisson', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'viande', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'couche', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'laitqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'changeqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'doudouqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'cqqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'mdqte', '' . "\0" . 'AppBundle\\Entity\\FicheInscription' . "\0" . 'biberonqte'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheInscription $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnfant($enfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnfant', [$enfant]);

        return parent::setEnfant($enfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnfant', []);

        return parent::getEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttente($attente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttente', [$attente]);

        return parent::setAttente($attente);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttente', []);

        return parent::getAttente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCraintes($craintes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCraintes', [$craintes]);

        return parent::setCraintes($craintes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCraintes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCraintes', []);

        return parent::getCraintes();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemarque($remarque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemarque', [$remarque]);

        return parent::setRemarque($remarque);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemarque', []);

        return parent::getRemarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriode($periode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriode', [$periode]);

        return parent::setPeriode($periode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriode', []);

        return parent::getPeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraire', []);

        return parent::getHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraire($horaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraire', [$horaire]);

        return parent::setHoraire($horaire);
    }

    /**
     * {@inheritDoc}
     */
    public function setAutorisation($autorisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutorisation', [$autorisation]);

        return parent::setAutorisation($autorisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutorisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutorisation', []);

        return parent::getAutorisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateinscription($dateinscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateinscription', [$dateinscription]);

        return parent::setDateinscription($dateinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateinscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateinscription', []);

        return parent::getDateinscription();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllergie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllergie', []);

        return parent::getAllergie();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllergie($allergie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllergie', [$allergie]);

        return parent::setAllergie($allergie);
    }

    /**
     * {@inheritDoc}
     */
    public function isMangeavecaide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMangeavecaide', []);

        return parent::isMangeavecaide();
    }

    /**
     * {@inheritDoc}
     */
    public function setMangeavecaide($mangeavecaide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMangeavecaide', [$mangeavecaide]);

        return parent::setMangeavecaide($mangeavecaide);
    }

    /**
     * {@inheritDoc}
     */
    public function isOeuf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOeuf', []);

        return parent::isOeuf();
    }

    /**
     * {@inheritDoc}
     */
    public function setOeuf($oeuf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOeuf', [$oeuf]);

        return parent::setOeuf($oeuf);
    }

    /**
     * {@inheritDoc}
     */
    public function isPoisson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPoisson', []);

        return parent::isPoisson();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoisson($poisson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoisson', [$poisson]);

        return parent::setPoisson($poisson);
    }

    /**
     * {@inheritDoc}
     */
    public function isViande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isViande', []);

        return parent::isViande();
    }

    /**
     * {@inheritDoc}
     */
    public function setViande($viande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViande', [$viande]);

        return parent::setViande($viande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouche()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouche', []);

        return parent::getCouche();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouche($couche)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouche', [$couche]);

        return parent::setCouche($couche);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaitqte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaitqte', []);

        return parent::getLaitqte();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaitqte($laitqte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaitqte', [$laitqte]);

        return parent::setLaitqte($laitqte);
    }

    /**
     * {@inheritDoc}
     */
    public function getChangeqte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChangeqte', []);

        return parent::getChangeqte();
    }

    /**
     * {@inheritDoc}
     */
    public function setChangeqte($changeqte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChangeqte', [$changeqte]);

        return parent::setChangeqte($changeqte);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoudouqte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoudouqte', []);

        return parent::getDoudouqte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoudouqte($doudouqte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoudouqte', [$doudouqte]);

        return parent::setDoudouqte($doudouqte);
    }

    /**
     * {@inheritDoc}
     */
    public function getCqqte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCqqte', []);

        return parent::getCqqte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCqqte($cqqte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCqqte', [$cqqte]);

        return parent::setCqqte($cqqte);
    }

    /**
     * {@inheritDoc}
     */
    public function getBiberonqte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBiberonqte', []);

        return parent::getBiberonqte();
    }

    /**
     * {@inheritDoc}
     */
    public function setBiberonqte($biberonqte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBiberonqte', [$biberonqte]);

        return parent::setBiberonqte($biberonqte);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdqte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdqte', []);

        return parent::getMdqte();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdqte($mdqte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdqte', [$mdqte]);

        return parent::setMdqte($mdqte);
    }

}
