<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Historiquepaiement extends \AppBundle\Entity\Historiquepaiement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'datedebut', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'datepaiement', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'datefin', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'rest', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'montanregler', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'paiement'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'datedebut', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'datepaiement', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'datefin', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'rest', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'montanregler', '' . "\0" . 'AppBundle\\Entity\\Historiquepaiement' . "\0" . 'paiement'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Historiquepaiement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatedebut($datedebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatedebut', [$datedebut]);

        return parent::setDatedebut($datedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatedebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatedebut', []);

        return parent::getDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefin($datefin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefin', [$datefin]);

        return parent::setDatefin($datefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefin', []);

        return parent::getDatefin();
    }

    /**
     * {@inheritDoc}
     */
    public function getRest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRest', []);

        return parent::getRest();
    }

    /**
     * {@inheritDoc}
     */
    public function setRest($rest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRest', [$rest]);

        return parent::setRest($rest);
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement($paiement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', [$paiement]);

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', []);

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontanregler()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontanregler', []);

        return parent::getMontanregler();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontanregler($montanregler)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontanregler', [$montanregler]);

        return parent::setMontanregler($montanregler);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatepaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatepaiement', []);

        return parent::getDatepaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatepaiement($datepaiement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatepaiement', [$datepaiement]);

        return parent::setDatepaiement($datepaiement);
    }

}
