<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \AppBundle\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'sender', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'recipient', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'dateSent', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'read', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'defaultprofile', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'contenue'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'sender', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'recipient', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'dateSent', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'read', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'defaultprofile', '' . "\0" . 'AppBundle\\Entity\\Message' . "\0" . 'contenue'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateSent($dateSent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateSent', [$dateSent]);

        return parent::setDateSent($dateSent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateSent', []);

        return parent::getDateSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setRead($read = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRead', [$read]);

        return parent::setRead($read);
    }

    /**
     * {@inheritDoc}
     */
    public function getRead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRead', []);

        return parent::getRead();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultprofile($defaultprofile = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultprofile', [$defaultprofile]);

        return parent::setDefaultprofile($defaultprofile);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultprofile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultprofile', []);

        return parent::getDefaultprofile();
    }

    /**
     * {@inheritDoc}
     */
    public function setSender(\AppBundle\Entity\User $sender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSender', [$sender]);

        return parent::setSender($sender);
    }

    /**
     * {@inheritDoc}
     */
    public function getSender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSender', []);

        return parent::getSender();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecipient(\AppBundle\Entity\User $recipient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecipient', [$recipient]);

        return parent::setRecipient($recipient);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipient', []);

        return parent::getRecipient();
    }

    /**
     * {@inheritDoc}
     */
    public function getContenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenue', []);

        return parent::getContenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenue($contenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenue', [$contenue]);

        return parent::setContenue($contenue);
    }

}
