<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Creche extends \AppBundle\Entity\Creche implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'heureOuverture', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'heurFermeture', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'nome', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'situation', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'tel', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'dateCreation', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'assurance', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'scolarite', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'fraisinscription'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'heureOuverture', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'heurFermeture', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'nome', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'situation', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'tel', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'dateCreation', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'assurance', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'scolarite', '' . "\0" . 'AppBundle\\Entity\\Creche' . "\0" . 'fraisinscription'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Creche $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureOuverture($heureOuverture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureOuverture', [$heureOuverture]);

        return parent::setHeureOuverture($heureOuverture);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureOuverture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureOuverture', []);

        return parent::getHeureOuverture();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeurFermeture($heurFermeture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeurFermeture', [$heurFermeture]);

        return parent::setHeurFermeture($heurFermeture);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeurFermeture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeurFermeture', []);

        return parent::getHeurFermeture();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function getAssurance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssurance', []);

        return parent::getAssurance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssurance($assurance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssurance', [$assurance]);

        return parent::setAssurance($assurance);
    }

    /**
     * {@inheritDoc}
     */
    public function getScolarite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScolarite', []);

        return parent::getScolarite();
    }

    /**
     * {@inheritDoc}
     */
    public function setScolarite($scolarite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScolarite', [$scolarite]);

        return parent::setScolarite($scolarite);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisinscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisinscription', []);

        return parent::getFraisinscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisinscription($fraisinscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisinscription', [$fraisinscription]);

        return parent::setFraisinscription($fraisinscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituation', []);

        return parent::getSituation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituation($situation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituation', [$situation]);

        return parent::setSituation($situation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

}
